/*
 ** TailwindCSS Configuration File
 **
 ** Docs: https://tailwindcss.com/docs/configuration
 ** Default: https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js
 */
module.exports = {
  theme: {
    extend: {
      backgroundColor: {
        overlay: 'rgba(255, 255, 255, 0.35)',
        'dark-overlay': 'rgba(0,0,0,.85)',
        pills: '#EAFAFC',
      },
      borderRadius: {
        60: '15rem',
        alert: '3rem',
        xl: '0.75rem',
      },
      borderWidth: {
        3: '3px',
        5: '5px',
      },
      boxShadow: {
        top: '0px -1px 3px rgba(0,0,0,.3)',
      },
      colors: {
        'light-gray': '#F9FAFB',
        'dark-green': '#285E61',
        'btn-normal': '#319795',
      },
      cursor: {
        grab: 'grab',
        grabbing: 'grabbing',
      },
      fontSize: {
        '3xl': '1.75rem',
        'extra-largest': '9rem',
        'extra-larger': '7rem',
        'extra-large': '5.75rem',
      },
      height: {
        screen: 'calc(var(--vh, 1vh) * 100)',
      },
      inset: {
        1.125: '0.36rem',
        '1/2': '50%',
        full: '100%',
      },
      linearGradientColors: {
        'light-teal': ['#EBF4FF', '#E6FFFA'],
        primary: ['#319795', '#3182CE'],
        'primary--hover': ['#2C7A7B', '#2B6CB0'],
        'primary--disabled': ['#B2F5EA', '#BEE3F8'],
        'primary--active': ['#285E61', '#2C5282'],
        'view-more': ['transparent', '#fff'],
      },
      margin: {
        '-1/5': '-20%',
        '-2/5': '-40%',
      },
      maxHeight: {
        initial: 'initial',
        screen: 'calc(var(--vh, 1vh) * 100)',
      },
      maxWidth: {
        23: '5.75rem',
      },
      minHeight: {
        12: '3rem',
        40: '10rem',
        116: '29rem',
        160: '40rem',
        auto: 'auto',
        screen: 'calc(var(--vh, 1vh) * 100 - 0.36rem)',
        'screen-minus-2': 'calc(var(--vh, 1vh) * 100 - 0.36rem)',
      },
      minWidth: {
        48: '12rem',
      },
      padding: {
        '1/3': '33.33%',
      },
      scale: {
        120: '1.2',
        140: '1.4',
      },
      screens: {
        '2xl': '1536px',
        '3xl': '1792px',
      },
      spacing: {
        1.125: '0.36rem',
        '1/2': '50%',
        '1/4': '25%',
        '1/8': '12.5%',
        7: '1.75rem',
        9: '2.25rem',
        14: '3.5rem',
        15: '3.75rem',
        18: '4.5rem',
        26: '6.5rem',
        28: '7rem',
        30: '7.5rem',
        36: '9rem',
        72: '18rem',
        80: '20rem',
        88: '22rem',
        96: '24rem',
        100: '25rem',
        120: '30rem',
        128: '32rem',
        cover: '25%',
        full: '100%',
      },
      zIndex: {
        1: '1',
        2: '2',
        60: '60',
        70: '70',
        80: '80',
        90: '90',
        100: '100',
      },
    },
    fontFamily: {
      sans: ['lato', 'sans-serif'],
    },
  },
  variants: {
    backgroundColor: [
      'responsive',
      'hover',
      'focus',
      'active',
      'group-hover',
      'disabled',
    ],
    borderWidth: ['responsive', 'hover', 'focus', 'group-hover'],
    borderColor: [
      'responsive',
      'hover',
      'focus',
      'active',
      'group-hover',
      'disabled',
    ],
    cursor: ['responsive', 'hover', 'focus', 'disabled'],
    linearGradients: ['responsive', 'hover', 'disabled', 'active'],
    margin: ['responsive', 'hover', 'focus', 'group-hover'],
    opacity: [
      'responsive',
      'hover',
      'focus',
      'active',
      'group-hover',
      'disabled',
    ],
    padding: ['responsive', 'hover', 'focus', 'group-hover'],
    textColor: [
      'responsive',
      'hover',
      'focus',
      'active',
      'group-hover',
      'disabled',
    ],
    textDecoration: [
      'responsive',
      'hover',
      'focus',
      'active',
      'group-hover',
      'disabled',
    ],
  },
  plugins: [require('tailwindcss-gradients')],
  purge: {
    // Learn more on https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
    enabled: process.env.NODE_ENV !== 'development',
    content: [
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.vue',
      'plugins/**/*.js',
      'nuxt.config.js',
    ],
    options: {
      whitelist: [
        'bg-red-100',
        'bg-teal-100',
        'bg-blue-100',
        'text-red-500',
        'text-teal-500',
        'text-blue-500',
        'text-red-600',
        'text-teal-600',
        'text-blue-600',
        'border-blue-600',
        'bg-red-500',
        'border-red-400',
        'border-yellow-400',
        'border-orange-400',
        'border-gray-400',
        'border-red-600',
        'border-teal-600',
        'border-yellow-600',
        'border-teal-400',
        'border-teal-600',
        'text-red-900',
        'text-blue-900',
        'text-yellow-900',
        'text-gray-900',
        'w-14',
        'h-14',
      ],
    },
  },
}
